#!/usr/bin/env bash

# TODO SOURCE: license_and_attribution
# TODO SOURCE: setup

# TODO: check if this file name overwrites another; fail gracefully
# TODO: add a second argument to name the downloaded folder

# TODO SOURCE: error_and_exit
# TODO SOURCE: command_info
# TODO SOURCE: basic_helper

read -r -d '' help_text <<'EOF'
usage: git grab <github_url> [<new_name>]

EOF

# TODO:
##     -v, --verbose         be verbose; must be placed before a subcommand
## EOF

# SOURCE: usage

# SOURCE: translate_url

main() {
  # SOURCE: print_usage_by_default

  # SOURCE: handle_options

  # TODO SOURCE: exit if invalid options or signature!

  git_url="${1}"
  svn_url="$(translateURL "$git_url")"
  svn export --force-interactive "$svn_url"
}

main "$@"
