#!/usr/bin/env bash

# TODO SOURCE: license_and_attribution

# TODO: check if downloaded is a folder or file

read -r -d '' help_text <<'EOF'
usage: git ls-sub <github_url>

EOF

# SOURCE: usage

# SOURCE: translate_url

main() {
  # SOURCE: print_usage_by_default

  # SOURCE: handle_options

  git_url="${1}"
  svn_url="$(translateURL "$git_url")"
  svn ls --force-interactive "$svn_url"
}

main "$@"
