#!/usr/bin/env bash
#        _ _                     _
#   __ _(_) |_    __ _ _ __ __ _| |__
#  / _` | | __|  / _` | '__/ _` | '_ \
# | (_| | | |_  | (_| | | | (_| | |_) |
#  \__, |_|\__|  \__, |_|  \__,_|_.__/
#  |___/         |___/
#
# Downloads a directory or file from a repository hosted on GitHub.
#
# SOURCE: license_and_attribution

# Here's how you use the command:
USAGE_TEXT="usage: git grab <github_url> [<new_name>]
"
# SOURCE: usage

# TODO:
##     -v, --verbose         be verbose; must be placed before a subcommand
## EOF

# TODO: setup

# TODO: check if this file name overwrites another; fail gracefully
# TODO: add a second argument to name the downloaded folder

# TODO: error_and_exit
# TODO: command_info
# TODO: basic_helper

# SOURCE: translate_url

########################################################################
#
# main is the program itself. Here is the code that we run when we
# invoke the command!
#
########################################################################
main() {
  # SOURCE: print_usage_by_default
  # SOURCE: handle_options

  # TODO: exit if invalid options or signature!

  git_url="${1}"
  svn_url="$(translate_url "$git_url")"
  svn export --force-interactive "$svn_url"
}

# Run the main command.
main "$@"
